---
- set_fact:
    reverse_dir: "{{ project_dir }}/rev_project_cloned"

- name: Install ansible
  dnf:
    name:
    - ansible
    state: present
  become: true
- name: Checkout packit
  git:
    clone: yes
    repo: https://github.com/packit-service/packit.git
    dest: "{{ reverse_dir }}"
- name: install packit dependencies via ansible playbooks
  command: ansible-playbook -e "ansible_python_interpreter=/usr/bin/python3" -v -c local -i localhost, files/zuul-install-requirements-pip.yaml
  args:
    chdir: "{{ reverse_dir }}"
- name: install and run basic packit tests via ansible playbooks
  command: ansible-playbook -e "ansible_python_interpreter=/usr/bin/python3" -v -c local -i localhost, files/zuul-tests.yaml
  args:
    chdir: "{{ reverse_dir }}"
- name: install and run packit tests with session recording via ansible playbooks
  command: ansible-playbook -e "ansible_python_interpreter=/usr/bin/python3" -v -c local -i localhost, files/zuul-tests-session-recording.yaml
  args:
    chdir: "{{ reverse_dir }}"
