---
- name: Install test rpm dependencies
  dnf:
    name:
      - python3-pip
      - python3-setuptools
      - git-core
      - python3-setuptools_scm
      - python3-setuptools_scm_git_archive
      - python3-wheel # for bdist_wheel
      - python3-pytest
      - python3-tox
      - python3-flexmock
    state: present
  become: true
- name: Install requre from git
  pip:
    name:
      - git+https://github.com/packit/requre.git
    state: latest
  become: true
